<template>
  <div>
    TABLE `business` (
    `businessId` '业务ID',
    `businessName` '业务名',
    `createTime` '创建时间',
    `updateTime` '更新时间',
    `deleteFlag` '删除标记',
    )
    CREATE TABLE `client` (
    `clientId` '客户ID',
    `clientName` '客户名称',
    `createTime` '创建时间',
    `updateTime` '更新时间',
    `deleteFlag` '删除标记',
    ) ;
    TABLE `client_to_business` (
    `clientId` '客户ID',
    `businessId` '业务ID',
    )
    TABLE `depType` (
    `typeId` '类型ID',
    `typeName` '类型名称',
    `deptId` '所属部门',
    `createTime` '创建时间',
    `updateTime` '更新时间',
    `deleteFlag` '删除标记'
    )
    CREATE TABLE `department` (
    `deptId`
    `deptName`
    `deptCode`
    `predeptId`
    `layer`
    `isSubNode`
    `principal`
    `isMaterial`
    `isPlatform` '(1:平台部门,2:创收执行部门)',
    `updateTime`
    `principalUserId`
    `deleteFlag` '是否删除(0:否,1:是)',
    `createTime`
    )
    TABLE `feedback` (
    `feedbackId` '反馈ID',
    `taskId` '所属客户ID，与task表对应',
    `initUserId` '任务发起人，对应user表ID',
    `feedback` '反馈详情',
    `updateTime` '更新时间',
    `deleteFlag` '删除标识',
    )
    CREATE TABLE `permission` (
    `id` '权限ID',
    `token` '权限标识',
    `name` '权限名',
    `pid` '父节点ID',
    )
    TABLE `proFile` (
    `fileId` '文档ID',
    `fileName` '文档名称',
    `suffix` '文档后缀',
    `localPath` '本地路径',
    `ptId` '所属项目ID或者任务ID，与project和task对应',
    `isPro` '项目任务需求（0-项目需求，1-任务需求）',
    `updateTime` '更新时间',
    `deleteFlag` '删除标记'
    )
    CREATE TABLE `project` (
    `proId` '项目ID',
    `proName` '项目名',
    `clientId` '所属客户ID，与client表对应',
    `serviceId` '所属业务ID ，与bussiness表对应',
    `isUsual` '专项日常（0-日常，1-专项）',
    `initUserId` '项目发起人，对应user表ID',
    `manager` '项目经理，对应user表ID',
    `department` '参与部门ID，用逗号隔开',
    `knowUser` '知情人ID，用逗号隔开',
    `createTime` '创建时间',
    `updateTime` '更新时间',
    `status` '项目状态（1-进行中，2-审核中，3-完成，4-延期，5-延期完成）',
    `delayReason` '项目延期原因',
    `overTime` '项目完成时间',
    `expertTime` '预计完成时间',
    `remark` '需求',
    `deleteFlag` '删除标记',
    )
    CREATE TABLE `role` (
    `roleId`T '角色ID',
    `roleName` '角色名称',
    `updateTime` '更新时间',
    `roleCode` '权限标识',
    )
    CREATE TABLE `role_to_permission` (
    `rid` '角色ID',
    `pid` '权限ID',
    )
    CREATE TABLE `task` (
    `taskId` '任务ID',
    `taskName` '任务名',
    `proId` '所属项目ID，与project表对应',
    `faTask` '所属任务ID ，与task表对应',
    `initUserId` '任务发起人',
    `doUserId` '任务参与人',
    `deptId` '所属部门ID，与dept对应',
    `isIgnore` '是否忽略（0-否，1-是）',
    `typeId` '任务类型ID，与depType表对应',
    `remark` '任务需求',
    `updateTime` '更新时间',
    `status` '任务状态（1-进行中，2-审核中，3-完成，4-延期，5-延期完成）',
    `overUserId` '任务完成人，与user表对应',
    `overDesc` '完成结果',
    `overTime` '完成时间',
    `expertTime` '预计完成时间',
    `deleteFlag` '删除标识',
    )
    CREATE TABLE `taskFile` (
    `fileId` '文档ID',
    `fileName` '文档名',
    `suffix` '文档后缀',
    `localPath` '本地路径',
    `proId` '所属项目ID',
    `taskId` '所属任务ID',
    `updateUserId` '文档更新人，与user表对应',
    `isHistory` '是否历史版本（0-否，1-是）',
    `nowEdition` '当前版本ID，对应文档ID',
    `createTime` '创建时间',
    `updateTime` '更新时间',
    `deleteFlag` '删除标记'
    )
    CREATE TABLE `users` (
    `userId` '用户ID',
    `userName` '用户名',
    `userPwd` '密码',
    `realName` '真是姓名',
    `deptId` '部门ID,deptId对应department表中的deptId',
    `deptName` '部门名称',
    `postId` '岗位ID,postId对应post表中的postId',
    `email` '邮箱',
    `QQ` 'QQ',
    `createTime` '创建时间',
    `wxuserId` '企业微信ID',
    `postName` '岗位名称',
    `roleId` '角色名称',
    `sex` '性别,0:男(默) 1:女',
    `updateTime` '更新时间',
    `deleteFlag` '删除标记',
    )
    {
    clientId: 37,
    clientName: "广汽",
    businessList: [
    {
    businessName: '官网',
    businessId: 12
    },
    {
    businessName: '数字营销',
    businessId: 2
    },
    ]
    }
    {
    clientId: "",
    clientName: "测试009",
    businessList: [
    {
    businessName: '官网',
    businessId: 12
    },
    {
    businessName: '数字营销',
    businessId: 2
    },
    ]
    }
  </div>
</template>

<script>
export default {
  name: 'sousuo',
  data() {},
  // 方法
  methods: {
    test() {
      let obj = [
        {
          createTime: '2020-03-08 13:31:14',
          deleteFlag: false,
          deptId: 27,
          deptName: null,
          doUserId: 9,
          doUserName: null,
          expertTime: '2020-03-15',
          faTask: 0,
          faTaskName: null,
          feedbackList: null,
          ignore: null,
          initUserId: 128,
          initUserName: null,
          isIgnore: null,
          listOaUser: null,
          listUserId: null,
          overDesc: null,
          overTime: null,
          overUserId: null,
          proFileList: null,
          proId: 33,
          proName: null,
          remark: null,
          status: 1,
          taskId: 62,
          taskName: '是是谁',
          taskfileList: [],
          typeId: null,
          typeName: null,
          updateTime: null
        },
        {
          createTime: '2020-03-04 19:38:10',
          deleteFlag: false,
          deptId: 27,
          deptName: null,
          doUserId: 3937,
          doUserName: null,
          expertTime: '2020-03-02',
          faTask: 0,
          faTaskName: null,
          feedbackList: null,
          ignore: true,
          initUserId: 128,
          initUserName: null,
          isIgnore: true,
          listOaUser: null,
          listUserId: null,
          overDesc: null,
          overTime: null,
          overUserId: null,
          proFileList: null,
          proId: 17,
          proName: null,
          remark: '需求',
          status: 1,
          taskId: 34,
          taskName: '后台',
          taskfileList: [],
          typeId: 2,
          typeName: null,
          updateTime: '2020-03-05 17:51:20'
        },
        {
          createTime: null,
          deleteFlag: false,
          deptId: 27,
          deptName: null,
          doUserId: 9,
          doUserName: null,
          expertTime: '2020-03-06',
          faTask: 0,
          faTaskName: null,
          feedbackList: null,
          ignore: null,
          initUserId: 128,
          initUserName: null,
          isIgnore: null,
          listOaUser: null,
          listUserId: null,
          overDesc: '333',
          overTime: null,
          overUserId: null,
          proFileList: null,
          proId: 31,
          proName: null,
          remark: null,
          status: 1,
          taskId: 58,
          taskName: '测试新建项目',
          taskfileList: [],
          typeId: null,
          typeName: null,
          updateTime: '2020-03-06 15:27:49'
        },
        {
          createTime: '2020-03-07 14:14:12',
          deleteFlag: false,
          deptId: 27,
          deptName: null,
          doUserId: 9,
          doUserName: null,
          expertTime: '2020-03-11',
          faTask: 0,
          faTaskName: null,
          feedbackList: null,
          ignore: null,
          initUserId: 128,
          initUserName: null,
          isIgnore: null,
          listOaUser: null,
          listUserId: null,
          overDesc: '',
          overTime: null,
          overUserId: null,
          proFileList: null,
          proId: 32,
          proName: null,
          remark: null,
          status: 2,
          taskId: 60,
          taskName: '官网项目新建测试',
          taskfileList: [
            {
              clientName: null,
              createTime: '2020-03-07 14:21:20',
              deleteFlag: false,
              fileId: 'W170B3A7BF5F23FE8BC80590',
              fileName: '新建文本文档',
              isHistory: 0,
              listUserId: null,
              localPath: 'uploadtemp/task/feedback/1583562075812.txt',
              nowEdition: '0',
              oldFileId: null,
              proId: 32,
              proName: null,
              realName: null,
              status: null,
              suffix: 'txt',
              taskId: 60,
              taskName: null,
              updateTime: '2020-03-07 14:21:20',
              updateUserId: 128,
              userName: null
            },
            {
              clientName: null,
              createTime: '2020-03-08 13:48:19',
              deleteFlag: false,
              fileId: 'W170B8AFDEBC13FE19792E6B',
              fileName: '架构',
              isHistory: 0,
              listUserId: null,
              localPath: 'uploadtemp/project/demand/1583646497154.jpg',
              nowEdition: '0',
              oldFileId: null,
              proId: 32,
              proName: null,
              realName: null,
              status: null,
              suffix: 'jpg',
              taskId: 60,
              taskName: null,
              updateTime: '2020-03-08 13:48:19',
              updateUserId: 128,
              userName: null
            },
            {
              clientName: null,
              createTime: '2020-03-08 13:48:33',
              deleteFlag: false,
              fileId: 'W170B8B018B123FEEBC16E5B',
              fileName: '丰田金服官网建设方案V1',
              isHistory: 0,
              listUserId: null,
              localPath: 'uploadtemp/project/demand/1583646512158.pdf',
              nowEdition: '0',
              oldFileId: null,
              proId: 32,
              proName: null,
              realName: null,
              status: null,
              suffix: 'pdf',
              taskId: 60,
              taskName: null,
              updateTime: '2020-03-08 13:48:33',
              updateUserId: 128,
              userName: null
            },
            {
              clientName: null,
              createTime: '2020-03-08 13:56:21',
              deleteFlag: false,
              fileId: 'W170B8B73D4133FB38CC8F9C',
              fileName: '闺蜜3',
              isHistory: 0,
              listUserId: null,
              localPath: 'uploadtemp/project/demand/1583646980085.jpg',
              nowEdition: '0',
              oldFileId: null,
              proId: 32,
              proName: null,
              realName: null,
              status: null,
              suffix: 'jpg',
              taskId: 60,
              taskName: null,
              updateTime: '2020-03-08 13:56:21',
              updateUserId: 128,
              userName: null
            },
            {
              clientName: null,
              createTime: '2020-03-08 14:00:23',
              deleteFlag: false,
              fileId: 'W170B8BAEB3113FED8ED9746',
              fileName: '刘666',
              isHistory: 0,
              listUserId: null,
              localPath: 'uploadtemp/project/demand/1583647212574.jpg',
              nowEdition: '0',
              oldFileId: null,
              proId: 32,
              proName: null,
              realName: null,
              status: null,
              suffix: 'jpg',
              taskId: 60,
              taskName: null,
              updateTime: '2020-03-08 14:00:23',
              updateUserId: 128,
              userName: null
            },
            {
              clientName: null,
              createTime: '2020-03-08 14:02:53',
              deleteFlag: false,
              fileId: 'W170B8BD365023FB3DCCC6DD',
              fileName: '母亲2',
              isHistory: 0,
              listUserId: null,
              localPath: 'uploadtemp/project/demand/1583647371663.jpg',
              nowEdition: '0',
              oldFileId: null,
              proId: 32,
              proName: null,
              realName: null,
              status: null,
              suffix: 'jpg',
              taskId: 60,
              taskName: null,
              updateTime: '2020-03-08 14:02:53',
              updateUserId: 128,
              userName: null
            }
          ],
          typeId: null,
          typeName: null,
          updateTime: '2020-03-08 12:31:21'
        },
        {
          createTime: '2020-03-02 23:55:55',
          deleteFlag: false,
          deptId: 27,
          deptName: null,
          doUserId: 128,
          doUserName: null,
          expertTime: '2020-03-02',
          faTask: 0,
          faTaskName: null,
          feedbackList: null,
          ignore: null,
          initUserId: 128,
          initUserName: null,
          isIgnore: null,
          listOaUser: null,
          listUserId: null,
          overDesc: '',
          overTime: null,
          overUserId: null,
          proFileList: null,
          proId: 6,
          proName: null,
          remark: '后台开发',
          status: 3,
          taskId: 18,
          taskName: '后台开发',
          taskfileList: [],
          typeId: 1,
          typeName: null,
          updateTime: '2020-03-03 23:19:33'
        },
        {
          createTime: null,
          deleteFlag: false,
          deptId: 27,
          deptName: null,
          doUserId: 1,
          doUserName: null,
          expertTime: null,
          faTask: 0,
          faTaskName: null,
          feedbackList: null,
          ignore: null,
          initUserId: 548,
          initUserName: null,
          isIgnore: null,
          listOaUser: null,
          listUserId: null,
          overDesc: '',
          overTime: null,
          overUserId: null,
          proFileList: null,
          proId: 1,
          proName: null,
          remark: '11111111111',
          status: 3,
          taskId: 1,
          taskName: '任务名称',
          taskfileList: [
            {
              clientName: null,
              createTime: '2020-02-20 18:45:07',
              deleteFlag: true,
              fileId: 'W1706232D5B113FEA2801C90',
              fileName: '研发部系统平台一组刘小龙一月日报表',
              isHistory: 0,
              listUserId: null,
              localPath:
                'D://VUE//pmbs_back//src//main//resources//static//file//研发部系统平台一组刘小龙一月日报表.xls',
              nowEdition: '0',
              oldFileId: null,
              proId: null,
              proName: null,
              realName: null,
              status: null,
              suffix: '.xls',
              taskId: 1,
              taskName: null,
              updateTime: '2020-02-20 18:45:08',
              updateUserId: 128,
              userName: null
            },
            {
              clientName: null,
              createTime: '2020-03-04 13:09:16',
              deleteFlag: true,
              fileId: 'W170A3F2AF0913FE63EF94E2',
              fileName: '2',
              isHistory: 0,
              listUserId: null,
              localPath: 'uploadtemp/task/feedback/1583298527240.jpg',
              nowEdition: '0',
              oldFileId: null,
              proId: 1,
              proName: null,
              realName: null,
              status: null,
              suffix: 'jpg',
              taskId: 1,
              taskName: null,
              updateTime: '2020-03-04 13:09:16',
              updateUserId: 128,
              userName: null
            }
          ],
          typeId: null,
          typeName: null,
          updateTime: '2020-03-04 13:13:01'
        },
        {
          createTime: '2020-03-05 19:16:51',
          deleteFlag: false,
          deptId: 27,
          deptName: null,
          doUserId: 9,
          doUserName: null,
          expertTime: '2020-03-04',
          faTask: 0,
          faTaskName: null,
          feedbackList: null,
          ignore: null,
          initUserId: 128,
          initUserName: null,
          isIgnore: null,
          listOaUser: null,
          listUserId: null,
          overDesc: '',
          overTime: null,
          overUserId: null,
          proFileList: null,
          proId: 3,
          proName: null,
          remark: '123123',
          status: 5,
          taskId: 50,
          taskName: '12321',
          taskfileList: [
            {
              clientName: null,
              createTime: '2020-03-05 19:41:54',
              deleteFlag: false,
              fileId: 'W170AA80845723FDA940ACB3',
              fileName: '架构',
              isHistory: 1,
              listUserId: null,
              localPath: 'uploadtemp/task/feedback/1583408512597.jpg',
              nowEdition: 'W170B8F3E60E13FE049034DA',
              oldFileId: null,
              proId: 3,
              proName: null,
              realName: null,
              status: null,
              suffix: 'jpg',
              taskId: 50,
              taskName: null,
              updateTime: '2020-03-05 19:41:54',
              updateUserId: 128,
              userName: null
            },
            {
              clientName: null,
              createTime: '2020-03-08 15:02:37',
              deleteFlag: false,
              fileId: 'W170B8F3E60E13FE049034DA',
              fileName: '架构',
              isHistory: 1,
              listUserId: null,
              localPath: 'uploadtemp/task/feedback/1583408512597.jpg',
              nowEdition: 'W170B8F84D8B23FEFE484FA5',
              oldFileId: null,
              proId: 3,
              proName: null,
              realName: null,
              status: null,
              suffix: 'jpg',
              taskId: 50,
              taskName: null,
              updateTime: '2020-03-05 19:41:54',
              updateUserId: 128,
              userName: null
            },
            {
              clientName: null,
              createTime: '2020-03-08 15:07:26',
              deleteFlag: false,
              fileId: 'W170B8F84D8B23FEFE484FA5',
              fileName: '闺蜜3',
              isHistory: 0,
              listUserId: null,
              localPath: 'uploadtemp/project/demand/1583651244548.jpg',
              nowEdition: '0',
              oldFileId: null,
              proId: 3,
              proName: null,
              realName: null,
              status: null,
              suffix: 'jpg',
              taskId: 50,
              taskName: null,
              updateTime: '2020-03-08 15:07:26',
              updateUserId: 128,
              userName: null
            }
          ],
          typeId: 2,
          typeName: null,
          updateTime: '2020-03-05 19:42:01'
        }
      ]

      // typeName typeId
    }
  },
  // 钩子函数
  mounted() {}
}
</script>